In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/main/Advertising.csv", index_col = 0)
data.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [ ]:
data.corr()

TV     radio  newspaper     sales
TV         1.000000  0.054809   0.056648  0.782224
radio      0.054809  1.000000   0.354104  0.576223
newspaper  0.056648  0.354104   1.000000  0.228299
sales      0.782224  0.576223   0.228299  1.000000

In [ ]:
sns

<module 'seaborn' from '/usr/local/lib/python3.10/dist-packages/seaborn/__init__.py'>

In [ ]:
X = data.iloc[:,:-1]
X.head()

TV  radio  newspaper
1  230.1   37.8       69.2
2   44.5   39.3       45.1
3   17.2   45.9       69.3
4  151.5   41.3       58.5
5  180.8   10.8       58.4

In [ ]:
y = data.iloc[:,-1]
y

1      22.1
2      10.4
3       9.3
4      18.5
5      12.9
       ... 
196     7.6
197     9.7
198    12.8
199    25.5
200    13.4
Name: sales, Length: 200, dtype: float64

In [ ]:
X.head()

TV  radio  newspaper
1  230.1   37.8       69.2
2   44.5   39.3       45.1
3   17.2   45.9       69.3
4  151.5   41.3       58.5
5  180.8   10.8       58.4

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=110)

In [ ]:
X_train.shape

(160, 3)

In [ ]:
X_test.shape

(40, 3)

In [ ]:
y_train.shape

(160,)

In [ ]:
y_test.shape

(40,)

In [ ]:
X_train.head()

TV  radio  newspaper
166  234.5    3.4       84.8
26   262.9    3.5       19.5
44   206.9    8.4       26.4
64   102.7   29.6        8.4
182  218.5    5.4       27.4

In [ ]:
X_test.head()

TV  radio  newspaper
169  215.4   23.6       57.6
198  177.0    9.3        6.4
148  243.2   49.0       44.3
125  229.5   32.3       74.2
141   73.4   17.0       12.9

In [ ]:
X_train.tail()

TV  radio  newspaper
90   109.8   47.8       51.4
126   87.2   11.8       25.9
16   195.4   47.7       52.9
62   261.3   42.7       54.7
129  220.3   49.0        3.2

In [ ]:
y_train

166    11.9
26     12.0
44     12.9
64     14.0
182    12.2
       ... 
90     16.7
126    10.6
16     22.4
62     24.2
129    24.7
Name: sales, Length: 160, dtype: float64

In [ ]:
y_test

169    17.1
198    12.8
148    25.4
125    19.7
141    10.9
66      9.3
152    11.6
21     18.0
72     12.4
87     12.0
42     17.1
101    11.7
29     18.9
28     15.9
120     6.6
43     20.7
186    22.6
56     23.7
199    25.5
80     11.0
119    15.9
139     9.6
31     21.4
188    17.3
83     11.3
78     14.2
54     21.2
192     9.9
136    11.6
11      8.6
93     19.4
39     10.1
117    12.2
184    26.2
116    12.6
30     10.5
162    13.3
106    19.2
7      11.8
112    21.8
Name: sales, dtype: float64

In [ ]:
X_train.describe()

TV       radio   newspaper
count  160.000000  160.000000  160.000000
mean   145.585000   22.281875   29.326250
std     86.935101   15.097481   21.766521
min      0.700000    0.000000    0.300000
25%     69.000000    8.350000   10.975000
50%    150.650000   20.950000   25.600000
75%    218.825000   36.525000   42.100000
max    296.400000   49.600000  114.000000

In [ ]:
X_train.columns

Index(['TV', 'radio', 'newspaper'], dtype='object')

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train[['TV', 'radio','newspaper']] = scaler.fit_transform(X_train[['TV', 'radio','newspaper']])
X_train.head()

TV     radio  newspaper
166  1.025986 -1.254591   2.556583
26   1.353692 -1.247946  -0.452856
44   0.707511 -0.922370  -0.134860
64  -0.494848  0.486247  -0.964415
182  0.841362 -1.121702  -0.088774

In [ ]:
X_train.describe()

TV         radio     newspaper
count  1.600000e+02  1.600000e+02  1.600000e+02
mean   2.220446e-17  3.053113e-17 -2.331468e-16
std    1.003140e+00  1.003140e+00  1.003140e+00
min   -1.671821e+00 -1.480501e+00 -1.337714e+00
25%   -8.837104e-01 -9.256920e-01 -8.457423e-01
50%    5.844478e-02 -8.849534e-02 -1.717293e-01
75%    8.451127e-01  9.463727e-01  5.886956e-01
max    1.740247e+00  1.815130e+00  3.902305e+00

In [ ]:
X_test.columns

Index(['TV', 'radio', 'newspaper'], dtype='object')

In [ ]:
X_test[['TV', 'radio','newspaper']] = scaler.fit_transform(X_test[['TV', 'radio','newspaper']])
X_test.head()

TV     radio  newspaper
169  0.770473 -0.274485   1.047823
198  0.297303 -1.367078  -1.375874
148  1.113029  1.666204   0.418230
125  0.944215  0.390239   1.833631
141 -0.979272 -0.778759  -1.068178

In [ ]:
from sklearn.linear_model import LinearRegression
regressor_best = LinearRegression()
regressor_best.fit(X_train, y_train)

LinearRegression()

In [ ]:
regressor_best

LinearRegression()

In [ ]:
regressor_best.intercept_

13.646875

In [ ]:
regressor_best.coef_

array([ 3.95814068,  2.79400747, -0.09238047])

In [ ]:
X_train.columns

Index(['TV', 'radio', 'newspaper'], dtype='object')

In [ ]:
y_pred_test = regressor_best.predict(X_test)
y_pred_test

array([15.83280285, 11.13111745, 22.66914931, 18.30515061,  7.69360036,
        5.8877088 ,  8.02273104, 16.87274149,  8.81032926, 10.06298723,
       16.13464824, 12.08822761, 18.36072753, 15.71624959,  4.80528657,
       20.76610631, 20.08148629, 20.52524803, 23.04946418,  7.74138476,
       14.20266172,  8.07761235, 20.67900525, 15.9086537 ,  8.40502825,
       12.44009225, 19.05281215,  6.50264376, 12.89293758,  4.89720726,
       18.05227444,  8.18942364, 10.27092496, 23.43354242, 11.44504057,
        7.22155092, 12.14768172, 16.91405207, 10.24468572, 20.34002178])

In [ ]:
print(y_test)

169    17.1
198    12.8
148    25.4
125    19.7
141    10.9
66      9.3
152    11.6
21     18.0
72     12.4
87     12.0
42     17.1
101    11.7
29     18.9
28     15.9
120     6.6
43     20.7
186    22.6
56     23.7
199    25.5
80     11.0
119    15.9
139     9.6
31     21.4
188    17.3
83     11.3
78     14.2
54     21.2
192     9.9
136    11.6
11      8.6
93     19.4
39     10.1
117    12.2
184    26.2
116    12.6
30     10.5
162    13.3
106    19.2
7      11.8
112    21.8
Name: sales, dtype: float64


In [ ]:
y_test.tail()

30     10.5
162    13.3
106    19.2
7      11.8
112    21.8
Name: sales, dtype: float64

In [ ]:
y_pred_train = regressor_best.predict(X_train)
y_pred_train

array([13.9663567 , 15.56004176, 13.88265227, 13.13586787, 13.85126252,
       14.68473857, 17.23033775,  3.54950832,  7.57606671, 14.67538867,
        6.32940174, 20.91347578,  5.70960309,  7.071668  , 18.08273271,
       14.89833875, 18.04613236, 12.3918165 ,  8.05681483, 12.06506241,
       15.23571754, 15.94967015, 12.63551063, 17.5673522 , 15.13518027,
        8.35971906, 14.17728819, 13.31382167, 14.06913954, 18.21963726,
       15.09886746, 16.40657987, 13.59576452, 10.69178118,  7.54021261,
       20.26306594, 16.67670201, 18.01929657, 22.95224526, 23.28598106,
       15.02614648,  9.96158785, 14.21960623, 11.99658089, 12.70028136,
        8.09256436, 16.79621757, 12.9999025 , 12.12222388,  9.82090687,
       11.55788051, 16.08547184, 18.88706695, 15.45365108, 11.48988898,
        8.71905616, 10.44381605, 11.44029693, 11.99758631,  7.58521202,
       18.38593381, 12.14203658, 18.22922491, 20.5759225 , 16.33768664,
       21.66126228, 14.5423076 , 12.33086492, 11.94081259,  8.76

In [ ]:
y_train

166    11.9
26     12.0
44     12.9
64     14.0
182    12.2
       ... 
90     16.7
126    10.6
16     22.4
62     24.2
129    24.7
Name: sales, Length: 160, dtype: float64

In [ ]:
X_test.tail()

TV     radio  newspaper
30  -1.013774 -0.855164   0.252547
162 -0.827709  0.657657   0.654919
106 -0.184493  1.467551   1.114096
7   -1.175194  0.428442  -0.566397
112  1.094545  0.825748  -0.580598

In [ ]:
y_pred_test

array([15.83280285, 11.13111745, 22.66914931, 18.30515061,  7.69360036,
        5.8877088 ,  8.02273104, 16.87274149,  8.81032926, 10.06298723,
       16.13464824, 12.08822761, 18.36072753, 15.71624959,  4.80528657,
       20.76610631, 20.08148629, 20.52524803, 23.04946418,  7.74138476,
       14.20266172,  8.07761235, 20.67900525, 15.9086537 ,  8.40502825,
       12.44009225, 19.05281215,  6.50264376, 12.89293758,  4.89720726,
       18.05227444,  8.18942364, 10.27092496, 23.43354242, 11.44504057,
        7.22155092, 12.14768172, 16.91405207, 10.24468572, 20.34002178])

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
R2_train = r2_score(y_train, y_pred_train)
R2_test = r2_score(y_test, y_pred_test)
print(R2_train," ",R2_test)

0.8823337069164685   0.8221608439158414
